### DeepSeek chat completion
POST https://api.deepseek.com/chat/completions
Content-Type: application/json
Authorization: Bearer {{$dotenv DEEPSEEK_API_KEY}}

{
  "model": "deepseek-v4-flash",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "what's the weather in NYC"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_weather",
        "description": "Get weather of a location, the user should supply a location first.",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA"
            }
          },
          "required": ["location"]
        }
      }
    }
  ],
  "thinking": {
    "type": "enabled"
  },
  "reasoning_effort": "low",
  "stream": false
}